apiVersion: v1
kind: Secret

metadata:
  name: backend-secret
  namespace: servicepulse

type: Opaque

stringData:

  DB_PASSWORD: servicepulse123

  GMAIL_USERNAME: likitha.2001feb@gmail.com

  GMAIL_PASSWORD: ffpxjgwlzkrvlgjk

  JWT_SECRET: smart-incident-management-secret-key-which-is-very-secure-123456